import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BackgroundGrid from "@/components/BackgroundGrid";

const fatKat = localFont({
  src: "./fonts/FatKat.otf",
  variable: "--font-fat-kat",
});

const proximaNova = localFont({
  src: "./fonts/ProximaNova-Regular.otf",
  variable: "--font-proxima-nova",
});

const kolRanko = localFont({
  src: "./fonts/kol-ranko.woff2",
  variable: "--font-kol-ranko",
});

const pixel = localFont({
  src: "./fonts/pixel.ttf",
  variable: "--font-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fatKat.variable} ${proximaNova.variable} ${kolRanko.variable} ${pixel.variable} antialiased`}
      >
        <BackgroundGrid />
        {children}
      </body>
    </html>
  );
}
